-keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*
-keep class com.uwu.animex.data.** { *; }
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-keep class coil3.network.** { *; }
-keep class com.uwu.animex.sync.** { *; }
